/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/ButterRobot.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ButterRobot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group175260438.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group382064065.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group80228427.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group575932120.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group2096540494.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group124309493.geometry} material={materials.mat17} />
      <mesh geometry={nodes.group1041594552.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group602582140.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group455168828.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group802730232.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group903096499.geometry} material={materials.mat3} />
      <mesh geometry={nodes.group1246658167.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group2137858386.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group2030767710.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group967698575.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1172343130.geometry} material={materials.mat25} />
      <mesh geometry={nodes.group290064353.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group294569758.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1408145829.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1026958873.geometry} material={materials.mat5} />
      <mesh geometry={nodes.group884107928.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group1112131118.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group125164161.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group457446437.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group536028838.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1378103587.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1597406385.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1604794717.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1166718152.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1704109605.geometry} material={materials.mat10} />
      <mesh geometry={nodes.group1522356135.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group601322296.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group618424017.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1223623961.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group54698192.geometry} material={materials.mat16} />
      <mesh geometry={nodes.group952658003.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1063360429.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group811062218.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group1775971220.geometry} material={materials.mat13} />
      <mesh geometry={nodes.group692528774.geometry} material={materials.mat12} />
      <mesh geometry={nodes.group1152383121.geometry} material={materials.mat15} />
      <mesh geometry={nodes.group1443680302.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1131850294.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1131850294_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1131850294_2.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh2141297075.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh2141297075_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh2141297075_2.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh246472840.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh246472840_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh246472840_2.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1983749940.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh1983749940_1.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh1983749940_2.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1983749940_3.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1983749940_4.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh1983749940_5.geometry} material={materials.mat21} />
      <mesh geometry={nodes.mesh1983749940_6.geometry} material={materials.mat24} />
      <mesh geometry={nodes.mesh1983749940_7.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1983749940_8.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1983749940_9.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh350132644.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh350132644_1.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh350132644_2.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh327530491.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh327530491_1.geometry} material={materials.mat7} />
      <mesh geometry={nodes.mesh327530491_2.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh327530491_3.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh327530491_4.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh327530491_5.geometry} material={materials.mat24} />
      <mesh geometry={nodes.mesh327530491_6.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh327530491_7.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh327530491_8.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh327530491_9.geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('/ButterRobot.glb')
