/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Chair.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair(props) {
  const { nodes, materials } = useGLTF('./models/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Office_Cha} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.Office_Cha_1} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.Office_Cha_2} />
    </group>
  )
}

useGLTF.preload('./models/Chair.glb')