/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Desk.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('./models/Desk.glb')
  return (
    <group {...props} dispose={null}>

      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat3} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('.models//Desk.glb')
