/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Table.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('./models/Table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat16} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat15} />
    </group>
  )
}

useGLTF.preload('./models/Table.glb')